#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MasonX-Request-ExtendedCompRoot-WithApacheSession
version:      0.03
version_from: lib/MasonX/Request/ExtendedCompRoot/WithApacheSession.pm
installdirs:  site
requires:
    MasonX::Request::WithApacheSession: 0.24
    MasonX::Request::ExtendedCompRoot: 0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
